// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCue9UncU_4CNKXG8qoGlThLzda8j16QC8',
    appId: '1:555913529829:web:357985ca0c464e9ce8870c',
    messagingSenderId: '555913529829',
    projectId: 'gestion-users-mobile',
    authDomain: 'gestion-users-mobile.firebaseapp.com',
    storageBucket: 'gestion-users-mobile.firebasestorage.app',
    measurementId: 'G-Z86T60YYLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTvCkE_9tbYGa4Bk0dFbWQXtKGNxq8BJE',
    appId: '1:555913529829:android:7c88e50856de1241e8870c',
    messagingSenderId: '555913529829',
    projectId: 'gestion-users-mobile',
    storageBucket: 'gestion-users-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCnbcJn4pvPwICooqShLgsAPmpZZtQKQ',
    appId: '1:555913529829:ios:cf6ff2023999a70ce8870c',
    messagingSenderId: '555913529829',
    projectId: 'gestion-users-mobile',
    storageBucket: 'gestion-users-mobile.firebasestorage.app',
    iosBundleId: 'com.example.application0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCnbcJn4pvPwICooqShLgsAPmpZZtQKQ',
    appId: '1:555913529829:ios:cf6ff2023999a70ce8870c',
    messagingSenderId: '555913529829',
    projectId: 'gestion-users-mobile',
    storageBucket: 'gestion-users-mobile.firebasestorage.app',
    iosBundleId: 'com.example.application0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCue9UncU_4CNKXG8qoGlThLzda8j16QC8',
    appId: '1:555913529829:web:587c700b0d4d3072e8870c',
    messagingSenderId: '555913529829',
    projectId: 'gestion-users-mobile',
    authDomain: 'gestion-users-mobile.firebaseapp.com',
    storageBucket: 'gestion-users-mobile.firebasestorage.app',
    measurementId: 'G-G6K2V250B3',
  );
}
